apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: controlplane-tls-cert
spec:
  dnsNames:
  - controlplane
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ingress-tls-cert
spec:
  dnsNames:
  - ingress
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: egress-tls-cert
spec:
  dnsNames:
  - egress
---