apiVersion: apps/v1
kind: Deployment
metadata:
  name: controlplane
spec:
  replicas: 3
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - controlplane
            topologyKey: "kubernetes.io/hostname"
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - controlplane
              topologyKey: "failure-domain.beta.kubernetes.io/zone"
      containers:
      - name: server
        args: [
          "--debug",
          "controlplane",
        ]
---
apiVersion: v1
kind: Service
metadata:
  name: controlplane
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  ports:
  - name: controlplane
    port: 19990
    $patch: delete
  - name: controlplane
    port: 443
    protocol: TCP
    targetPort: 19990