apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-example-app

commonLabels:
  env: staging

bases:
- ../example-app

resources:
- namespace.yaml

patchesStrategicMerge:
- certificates.yaml
- reports-server.yaml

images:
- name: reports-server
