apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnative

commonLabels:
  env: staging

bases:
- ../base

resources:
- namespace.yaml

patchesStrategicMerge:
- certificates.yaml
- controlplane.yaml
- ingress.yaml
- egress.yaml
- logplexd.yaml

images:
- name: controlplane
- name: egress
- name: ingress
- name: logplexd
