apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports-server
spec:
  replicas: 3
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: service
                operator: In
                values:
                - reports
            topologyKey: "kubernetes.io/hostname"
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: service
                  operator: In
                  values:
                  - reports
              topologyKey: "failure-domain.beta.kubernetes.io/zone"
      containers:
      - name: reports-server
        args: [
          "--debug",
          "reports",
        ]