// Code generated by protoc-gen-go. DO NOT EDIT.
// source: report.proto

package api

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FilterReportsRequestSortOrder int32

const (
	FilterReportsRequest_SORT_ASC  FilterReportsRequestSortOrder = 0
	FilterReportsRequest_SORT_DESC FilterReportsRequestSortOrder = 1
)

var FilterReportsRequestSortOrder_name = map[int32]string{
	0: "SORT_ASC",
	1: "SORT_DESC",
}

var FilterReportsRequestSortOrder_value = map[string]int32{
	"SORT_ASC":  0,
	"SORT_DESC": 1,
}

func (x FilterReportsRequestSortOrder) String() string {
	return proto.EnumName(FilterReportsRequestSortOrder_name, int32(x))
}

func (FilterReportsRequestSortOrder) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3eedb623aa6ca98c, []int{2, 0}
}

type CreateReportRequest struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels               map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateReportRequest) Reset()         { *m = CreateReportRequest{} }
func (m *CreateReportRequest) String() string { return proto.CompactTextString(m) }
func (*CreateReportRequest) ProtoMessage()    {}
func (*CreateReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eedb623aa6ca98c, []int{0}
}

func (m *CreateReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReportRequest.Unmarshal(m, b)
}
func (m *CreateReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReportRequest.Marshal(b, m, deterministic)
}
func (m *CreateReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReportRequest.Merge(m, src)
}
func (m *CreateReportRequest) XXX_Size() int {
	return xxx_messageInfo_CreateReportRequest.Size(m)
}
func (m *CreateReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReportRequest proto.InternalMessageInfo

func (m *CreateReportRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateReportRequest) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type CreateReportResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Labels               map[string]string    `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatedBy            string               `protobuf:"bytes,51,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy            string               `protobuf:"bytes,52,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,53,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,54,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateReportResponse) Reset()         { *m = CreateReportResponse{} }
func (m *CreateReportResponse) String() string { return proto.CompactTextString(m) }
func (*CreateReportResponse) ProtoMessage()    {}
func (*CreateReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eedb623aa6ca98c, []int{1}
}

func (m *CreateReportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReportResponse.Unmarshal(m, b)
}
func (m *CreateReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReportResponse.Marshal(b, m, deterministic)
}
func (m *CreateReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReportResponse.Merge(m, src)
}
func (m *CreateReportResponse) XXX_Size() int {
	return xxx_messageInfo_CreateReportResponse.Size(m)
}
func (m *CreateReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReportResponse proto.InternalMessageInfo

func (m *CreateReportResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateReportResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateReportResponse) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *CreateReportResponse) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *CreateReportResponse) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *CreateReportResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *CreateReportResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type FilterReportsRequest struct {
	Name                 string                        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels               map[string]string             `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Page                 int32                         `protobuf:"varint,11,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32                         `protobuf:"varint,12,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy               []string                      `protobuf:"bytes,13,rep,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortingOrder         FilterReportsRequestSortOrder `protobuf:"varint,14,opt,name=sorting_order,json=sortingOrder,proto3,enum=api.FilterReportsRequestSortOrder" json:"sorting_order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *FilterReportsRequest) Reset()         { *m = FilterReportsRequest{} }
func (m *FilterReportsRequest) String() string { return proto.CompactTextString(m) }
func (*FilterReportsRequest) ProtoMessage()    {}
func (*FilterReportsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eedb623aa6ca98c, []int{2}
}

func (m *FilterReportsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterReportsRequest.Unmarshal(m, b)
}
func (m *FilterReportsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterReportsRequest.Marshal(b, m, deterministic)
}
func (m *FilterReportsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterReportsRequest.Merge(m, src)
}
func (m *FilterReportsRequest) XXX_Size() int {
	return xxx_messageInfo_FilterReportsRequest.Size(m)
}
func (m *FilterReportsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterReportsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FilterReportsRequest proto.InternalMessageInfo

func (m *FilterReportsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FilterReportsRequest) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *FilterReportsRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *FilterReportsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *FilterReportsRequest) GetSortBy() []string {
	if m != nil {
		return m.SortBy
	}
	return nil
}

func (m *FilterReportsRequest) GetSortingOrder() FilterReportsRequestSortOrder {
	if m != nil {
		return m.SortingOrder
	}
	return FilterReportsRequest_SORT_ASC
}

type FilterReportsResponse struct {
	Reports              []*FilterReportsResponseItem `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *FilterReportsResponse) Reset()         { *m = FilterReportsResponse{} }
func (m *FilterReportsResponse) String() string { return proto.CompactTextString(m) }
func (*FilterReportsResponse) ProtoMessage()    {}
func (*FilterReportsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eedb623aa6ca98c, []int{3}
}

func (m *FilterReportsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterReportsResponse.Unmarshal(m, b)
}
func (m *FilterReportsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterReportsResponse.Marshal(b, m, deterministic)
}
func (m *FilterReportsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterReportsResponse.Merge(m, src)
}
func (m *FilterReportsResponse) XXX_Size() int {
	return xxx_messageInfo_FilterReportsResponse.Size(m)
}
func (m *FilterReportsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterReportsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FilterReportsResponse proto.InternalMessageInfo

func (m *FilterReportsResponse) GetReports() []*FilterReportsResponseItem {
	if m != nil {
		return m.Reports
	}
	return nil
}

type FilterReportsResponseItem struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Labels               map[string]string    `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatedBy            string               `protobuf:"bytes,51,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy            string               `protobuf:"bytes,52,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,53,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,54,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FilterReportsResponseItem) Reset()         { *m = FilterReportsResponseItem{} }
func (m *FilterReportsResponseItem) String() string { return proto.CompactTextString(m) }
func (*FilterReportsResponseItem) ProtoMessage()    {}
func (*FilterReportsResponseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eedb623aa6ca98c, []int{3, 0}
}

func (m *FilterReportsResponseItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterReportsResponseItem.Unmarshal(m, b)
}
func (m *FilterReportsResponseItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterReportsResponseItem.Marshal(b, m, deterministic)
}
func (m *FilterReportsResponseItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterReportsResponseItem.Merge(m, src)
}
func (m *FilterReportsResponseItem) XXX_Size() int {
	return xxx_messageInfo_FilterReportsResponseItem.Size(m)
}
func (m *FilterReportsResponseItem) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterReportsResponseItem.DiscardUnknown(m)
}

var xxx_messageInfo_FilterReportsResponseItem proto.InternalMessageInfo

func (m *FilterReportsResponseItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FilterReportsResponseItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FilterReportsResponseItem) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *FilterReportsResponseItem) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *FilterReportsResponseItem) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *FilterReportsResponseItem) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *FilterReportsResponseItem) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type GetReportRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReportRequest) Reset()         { *m = GetReportRequest{} }
func (m *GetReportRequest) String() string { return proto.CompactTextString(m) }
func (*GetReportRequest) ProtoMessage()    {}
func (*GetReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eedb623aa6ca98c, []int{4}
}

func (m *GetReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReportRequest.Unmarshal(m, b)
}
func (m *GetReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReportRequest.Marshal(b, m, deterministic)
}
func (m *GetReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReportRequest.Merge(m, src)
}
func (m *GetReportRequest) XXX_Size() int {
	return xxx_messageInfo_GetReportRequest.Size(m)
}
func (m *GetReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetReportRequest proto.InternalMessageInfo

func (m *GetReportRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetReportResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Labels               map[string]string    `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatedBy            string               `protobuf:"bytes,51,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy            string               `protobuf:"bytes,52,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,53,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,54,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetReportResponse) Reset()         { *m = GetReportResponse{} }
func (m *GetReportResponse) String() string { return proto.CompactTextString(m) }
func (*GetReportResponse) ProtoMessage()    {}
func (*GetReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eedb623aa6ca98c, []int{5}
}

func (m *GetReportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReportResponse.Unmarshal(m, b)
}
func (m *GetReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReportResponse.Marshal(b, m, deterministic)
}
func (m *GetReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReportResponse.Merge(m, src)
}
func (m *GetReportResponse) XXX_Size() int {
	return xxx_messageInfo_GetReportResponse.Size(m)
}
func (m *GetReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetReportResponse proto.InternalMessageInfo

func (m *GetReportResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetReportResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetReportResponse) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *GetReportResponse) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *GetReportResponse) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *GetReportResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *GetReportResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.FilterReportsRequestSortOrder", FilterReportsRequestSortOrder_name, FilterReportsRequestSortOrder_value)
	proto.RegisterType((*CreateReportRequest)(nil), "api.CreateReportRequest")
	proto.RegisterMapType((map[string]string)(nil), "api.CreateReportRequest.LabelsEntry")
	proto.RegisterType((*CreateReportResponse)(nil), "api.CreateReportResponse")
	proto.RegisterMapType((map[string]string)(nil), "api.CreateReportResponse.LabelsEntry")
	proto.RegisterType((*FilterReportsRequest)(nil), "api.FilterReportsRequest")
	proto.RegisterMapType((map[string]string)(nil), "api.FilterReportsRequest.LabelsEntry")
	proto.RegisterType((*FilterReportsResponse)(nil), "api.FilterReportsResponse")
	proto.RegisterType((*FilterReportsResponseItem)(nil), "api.FilterReportsResponse.item")
	proto.RegisterMapType((map[string]string)(nil), "api.FilterReportsResponse.item.LabelsEntry")
	proto.RegisterType((*GetReportRequest)(nil), "api.GetReportRequest")
	proto.RegisterType((*GetReportResponse)(nil), "api.GetReportResponse")
	proto.RegisterMapType((map[string]string)(nil), "api.GetReportResponse.LabelsEntry")
}

func init() { proto.RegisterFile("report.proto", fileDescriptor_3eedb623aa6ca98c) }

var fileDescriptor_3eedb623aa6ca98c = []byte{
	// 736 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x56, 0xcb, 0x6e, 0xd3, 0x4c,
	0x14, 0xfe, 0xed, 0xf4, 0x96, 0x93, 0x8b, 0xf2, 0x4f, 0xda, 0xe2, 0xba, 0xa0, 0x5a, 0x16, 0x48,
	0xe1, 0x52, 0x5b, 0xb4, 0x80, 0x48, 0x44, 0x17, 0x49, 0x68, 0x11, 0x02, 0x51, 0xc9, 0xa9, 0x84,
	0xc4, 0xa2, 0xd1, 0x24, 0x19, 0xdc, 0x11, 0x89, 0xc7, 0xd8, 0x93, 0x40, 0x8a, 0xd8, 0xf0, 0x08,
	0xf0, 0x06, 0xbc, 0x02, 0x8f, 0xc2, 0x9e, 0x05, 0xea, 0x82, 0x47, 0x60, 0x89, 0x3c, 0x76, 0xd2,
	0xc4, 0x38, 0x14, 0xd4, 0x6d, 0x57, 0x9e, 0x39, 0xf3, 0x9d, 0x6f, 0x4e, 0xbe, 0x73, 0x99, 0x40,
	0xd6, 0x23, 0x2e, 0xf3, 0xb8, 0xe1, 0x7a, 0x8c, 0x33, 0x94, 0xc2, 0x2e, 0x55, 0x2f, 0xdb, 0x8c,
	0xd9, 0x5d, 0x62, 0x62, 0x97, 0x9a, 0xd8, 0x71, 0x18, 0xc7, 0x9c, 0x32, 0xc7, 0x0f, 0x21, 0xea,
	0x2d, 0xf1, 0x69, 0x6f, 0xda, 0xc4, 0xd9, 0xf4, 0xdf, 0x60, 0xdb, 0x26, 0x9e, 0xc9, 0x5c, 0x81,
	0x48, 0x40, 0x6f, 0x44, 0x5c, 0x62, 0xd7, 0xea, 0xbf, 0x34, 0x39, 0xed, 0x11, 0x9f, 0xe3, 0x9e,
	0x1b, 0x02, 0xf4, 0xcf, 0x12, 0x14, 0xeb, 0x1e, 0xc1, 0x9c, 0x58, 0x22, 0x10, 0x8b, 0xbc, 0xee,
	0x13, 0x9f, 0x23, 0x04, 0x73, 0x0e, 0xee, 0x11, 0x45, 0xd2, 0xa4, 0x52, 0xda, 0x12, 0x6b, 0xf4,
	0x00, 0x16, 0xba, 0xb8, 0x45, 0xba, 0xbe, 0x22, 0x6b, 0xa9, 0x52, 0x66, 0xeb, 0xaa, 0x81, 0x5d,
	0x6a, 0x24, 0x78, 0x1b, 0x4f, 0x05, 0x6c, 0xd7, 0xe1, 0xde, 0xd0, 0x8a, 0x7c, 0xd4, 0x32, 0x64,
	0x26, 0xcc, 0xa8, 0x00, 0xa9, 0x57, 0x64, 0x18, 0xf1, 0x07, 0x4b, 0xb4, 0x0c, 0xf3, 0x03, 0xdc,
	0xed, 0x13, 0x45, 0x16, 0xb6, 0x70, 0x53, 0x91, 0xef, 0x4b, 0xfa, 0x0f, 0x19, 0x96, 0xa7, 0xaf,
	0xf1, 0x5d, 0xe6, 0xf8, 0x04, 0xe5, 0x41, 0xa6, 0x9d, 0x88, 0x43, 0xa6, 0x9d, 0x71, 0xd4, 0xf2,
	0x44, 0xd4, 0x3b, 0xe3, 0xa8, 0x53, 0x22, 0xea, 0x6b, 0x09, 0x51, 0x87, 0x74, 0x49, 0x61, 0xa3,
	0x2b, 0x00, 0x6d, 0x81, 0xed, 0x34, 0x5b, 0x43, 0x65, 0x5b, 0x10, 0xa7, 0x23, 0x4b, 0x6d, 0x18,
	0x1c, 0xf7, 0xdd, 0xce, 0xe8, 0xf8, 0x4e, 0x78, 0x1c, 0x59, 0x6a, 0x43, 0x54, 0x3e, 0xf5, 0xc6,
	0x5c, 0xb9, 0xab, 0x49, 0xa5, 0xcc, 0x96, 0x6a, 0x84, 0x49, 0x31, 0x46, 0x49, 0x31, 0x0e, 0x46,
	0x49, 0x19, 0x33, 0x57, 0x79, 0xe0, 0x3a, 0x62, 0xc6, 0x5c, 0xb9, 0x77, 0xb6, 0x6b, 0x84, 0xae,
	0xf2, 0xf3, 0x48, 0x7d, 0x22, 0xc3, 0xf2, 0x1e, 0xed, 0x72, 0xe2, 0x85, 0xda, 0xf8, 0x7f, 0x2a,
	0x88, 0x9d, 0x58, 0x41, 0x84, 0xd2, 0x26, 0xb9, 0x27, 0x4a, 0x8b, 0x60, 0xce, 0xc5, 0x36, 0x51,
	0x32, 0x9a, 0x54, 0x9a, 0xb7, 0xc4, 0x1a, 0xad, 0x43, 0x3a, 0xf8, 0x36, 0x7d, 0x7a, 0x4c, 0x94,
	0xac, 0x38, 0x58, 0x0a, 0x0c, 0x0d, 0x7a, 0x4c, 0xd0, 0x25, 0x58, 0xf4, 0x99, 0xc7, 0x03, 0xa5,
	0x73, 0x5a, 0xaa, 0x94, 0xb6, 0x16, 0x82, 0x6d, 0x6d, 0x88, 0x1e, 0x43, 0x2e, 0x58, 0x51, 0xc7,
	0x6e, 0x32, 0xaf, 0x43, 0x3c, 0x25, 0xaf, 0x49, 0xa5, 0x7c, 0x54, 0xa0, 0x89, 0xf1, 0x08, 0x1e,
	0x81, 0xb5, 0xb2, 0x91, 0xeb, 0x7e, 0xb0, 0x3b, 0x8f, 0x76, 0xd7, 0x01, 0x4e, 0x69, 0x51, 0x16,
	0x96, 0x1a, 0xfb, 0xd6, 0x41, 0xb3, 0xda, 0xa8, 0x17, 0xfe, 0x43, 0x39, 0x48, 0x8b, 0xdd, 0xc3,
	0xdd, 0x46, 0xbd, 0x20, 0xe9, 0x5f, 0x52, 0xb0, 0x12, 0x8b, 0x2b, 0x2a, 0xe9, 0x32, 0x2c, 0x86,
	0x23, 0xc1, 0x57, 0x24, 0x21, 0xea, 0x46, 0xd2, 0x8f, 0x88, 0x0a, 0x96, 0x72, 0xd2, 0xb3, 0x46,
	0x78, 0xf5, 0x9b, 0x0c, 0x73, 0x81, 0xe5, 0xaf, 0xda, 0xa2, 0x1e, 0x6b, 0x8b, 0x9b, 0x67, 0x5c,
	0x73, 0xd1, 0x1c, 0x92, 0xae, 0x43, 0xe1, 0x11, 0xe1, 0xd3, 0x83, 0x32, 0xa6, 0xb5, 0xfe, 0x5d,
	0x86, 0xff, 0x27, 0x40, 0xff, 0x30, 0xa8, 0x2a, 0xb1, 0x8c, 0xe8, 0x22, 0x23, 0xbf, 0x71, 0x5d,
	0x24, 0x42, 0xda, 0xfa, 0x29, 0x43, 0x2e, 0x54, 0xa5, 0x41, 0xbc, 0x01, 0x6d, 0x13, 0x74, 0x08,
	0xd9, 0xc9, 0x91, 0x8e, 0x94, 0x59, 0x6f, 0x93, 0xba, 0x36, 0x73, 0xfe, 0xeb, 0x6b, 0x1f, 0xbe,
	0x9e, 0x7c, 0x92, 0x8b, 0x7a, 0x5e, 0xbc, 0xbd, 0x83, 0xdb, 0x66, 0xd8, 0x59, 0x15, 0xe9, 0x06,
	0x3a, 0x84, 0xdc, 0x54, 0x6f, 0xa0, 0xb5, 0x99, 0xb3, 0x45, 0x55, 0x67, 0xb7, 0x92, 0xbe, 0x2a,
	0xae, 0x28, 0xa0, 0xd8, 0x15, 0xe8, 0x39, 0xa4, 0xc7, 0x99, 0x46, 0x2b, 0xf1, 0xcc, 0x87, 0xbc,
	0xab, 0xc9, 0x05, 0xa1, 0xaf, 0x0b, 0xce, 0x15, 0x54, 0x9c, 0xe6, 0x34, 0xdf, 0xd1, 0xce, 0x7b,
	0xf5, 0xd9, 0xc7, 0xea, 0x13, 0x94, 0x0f, 0x3d, 0xb4, 0x48, 0x2d, 0xb5, 0x0c, 0xc5, 0x3d, 0xea,
	0x74, 0x34, 0xd6, 0xe7, 0x5a, 0x8f, 0x79, 0x44, 0xc3, 0x2d, 0xd6, 0xe7, 0x48, 0x3f, 0xe2, 0xdc,
	0xf5, 0x2b, 0xa6, 0x69, 0x53, 0x7e, 0xd4, 0x6f, 0x19, 0x6d, 0xd6, 0x33, 0xdb, 0x0e, 0xe6, 0x74,
	0x40, 0x4c, 0xf2, 0x16, 0xf7, 0xdc, 0x2e, 0xa9, 0xcd, 0xbf, 0x08, 0xfe, 0xa4, 0xb4, 0x16, 0x44,
	0x6e, 0xb7, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x2d, 0xaa, 0xc1, 0xe2, 0xc0, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReportServiceClient is the client API for ReportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReportServiceClient interface {
	CreateReport(ctx context.Context, in *CreateReportRequest, opts ...grpc.CallOption) (*CreateReportResponse, error)
	FilterReports(ctx context.Context, in *FilterReportsRequest, opts ...grpc.CallOption) (*FilterReportsResponse, error)
	GetReport(ctx context.Context, in *GetReportRequest, opts ...grpc.CallOption) (*GetReportResponse, error)
}

type reportServiceClient struct {
	cc *grpc.ClientConn
}

func NewReportServiceClient(cc *grpc.ClientConn) ReportServiceClient {
	return &reportServiceClient{cc}
}

func (c *reportServiceClient) CreateReport(ctx context.Context, in *CreateReportRequest, opts ...grpc.CallOption) (*CreateReportResponse, error) {
	out := new(CreateReportResponse)
	err := c.cc.Invoke(ctx, "/api.ReportService/CreateReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) FilterReports(ctx context.Context, in *FilterReportsRequest, opts ...grpc.CallOption) (*FilterReportsResponse, error) {
	out := new(FilterReportsResponse)
	err := c.cc.Invoke(ctx, "/api.ReportService/FilterReports", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) GetReport(ctx context.Context, in *GetReportRequest, opts ...grpc.CallOption) (*GetReportResponse, error) {
	out := new(GetReportResponse)
	err := c.cc.Invoke(ctx, "/api.ReportService/GetReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportServiceServer is the server API for ReportService service.
type ReportServiceServer interface {
	CreateReport(context.Context, *CreateReportRequest) (*CreateReportResponse, error)
	FilterReports(context.Context, *FilterReportsRequest) (*FilterReportsResponse, error)
	GetReport(context.Context, *GetReportRequest) (*GetReportResponse, error)
}

// UnimplementedReportServiceServer can be embedded to have forward compatible implementations.
type UnimplementedReportServiceServer struct {
}

func (*UnimplementedReportServiceServer) CreateReport(ctx context.Context, req *CreateReportRequest) (*CreateReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReport not implemented")
}
func (*UnimplementedReportServiceServer) FilterReports(ctx context.Context, req *FilterReportsRequest) (*FilterReportsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FilterReports not implemented")
}
func (*UnimplementedReportServiceServer) GetReport(ctx context.Context, req *GetReportRequest) (*GetReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReport not implemented")
}

func RegisterReportServiceServer(s *grpc.Server, srv ReportServiceServer) {
	s.RegisterService(&_ReportService_serviceDesc, srv)
}

func _ReportService_CreateReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).CreateReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ReportService/CreateReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).CreateReport(ctx, req.(*CreateReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_FilterReports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterReportsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).FilterReports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ReportService/FilterReports",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).FilterReports(ctx, req.(*FilterReportsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_GetReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ReportService/GetReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetReport(ctx, req.(*GetReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReportService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.ReportService",
	HandlerType: (*ReportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateReport",
			Handler:    _ReportService_CreateReport_Handler,
		},
		{
			MethodName: "FilterReports",
			Handler:    _ReportService_FilterReports_Handler,
		},
		{
			MethodName: "GetReport",
			Handler:    _ReportService_GetReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "report.proto",
}
