apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: server-cert-issuer
spec:
  ca:
    secretName: self-signed-ca-tls-key
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: client-cert-issuer
spec:
  ca:
    secretName: self-signed-ca-tls-key