apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: server-cert-issuer
spec:
  ca:
    secretName: self-signed-ca-tls-key
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: client-cert-issuer
spec:
  ca:
    secretName: self-signed-ca-tls-key