apiVersion: apps/v1
kind: Deployment
metadata:
  name: controlplane
  labels:
    app: controlplane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controlplane
  template:
    metadata:
      labels:
        app: controlplane
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      volumes:
      - name: tls-cert
        secret:
          secretName: controlplane-tls-cert
      containers:
      - name: server
        image: controlplane
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        args: [
          "controlplane"
        ]
        env:
          - name: TLS_CERT_DIR
            value: /etc/cnative/server/certs
        volumeMounts:
        - name: tls-cert
          mountPath: /etc/cnative/server/certs
        ports:
        - name: server
          containerPort: 19990
          protocol: TCP
        - name: health
          containerPort: 19992
          protocol: TCP
        - name: metrics
          containerPort: 9101
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /live
            port: 19992
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 19992
---
apiVersion: v1
kind: Service
metadata:
  name: controlplane
  labels:
    app: controlplane
spec:
  ports:
  - name:  controlplane
    port: 19990
    protocol: TCP
    targetPort: 19990
  selector:
    app: controlplane
