apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: self-signed-ca-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: self-signed-ca-cert
spec:
  secretName: self-signed-ca-tls-key
  commonName: cnative-ca
  isCA: true
  issuerRef:
    name: self-signed-ca-issuer
    kind: Issuer