apiVersion: apps/v1
kind: Deployment
metadata:
  name: controlplane
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: server
        imagePullPolicy: Never
        args: [
          "--debug",
          "controlplane"
        ]