apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: e2e-tests

commonLabels:
  env: integ-test

bases:
- ../base

resources:
  - namespace.yaml

patchesStrategicMerge:
  - certificates.yaml
  - reports-server.yaml

vars:
- name: SERVICEACCOUNT_NAMESPACE
  objref:
    apiVersion: v1
    kind: ServiceAccount
    name: integ-test-sa
  fieldref:
    fieldpath: metadata.namespace

images:
- name: reports-server
  newTag: integ
