apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: example-app-reports-db
spec:
  teamId: "example-app"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    sduser:  # database owner
    - superuser
    - createdb
  databases:
    reports: sduser  # dbname: owner
  postgresql:
    version: "12"
---
